### ISSUE TITLE
PBI - Criar o fluxo de upload com PDF

### ISSUE THREAD

**Issue by ceduardoferreira** [gepetojj/shelf#1]
# Descrição
- Conseguir fazer o upload de um arquivo PDF no Shelf.

# Due date
- 06/06/2024

# História de usuário 
- Eu como usuário, gostaria de fazer upload de meus arquivos PDFs no Shelf para poder posteriormente localizá-los na minha estante de arquivos e posterior a isso novamente, poder ler e editar meus arquivos. 

# Tasks
- [x] Registrar e armazenar o arquivo
- [x] Mostrar o arquivo no feed e na estante

**Comment by gepetojj** [comment]
implementado no commit fa219bb
