### ISSUE TITLE
BUG - login

### ISSUE THREAD

**Issue by ceduardoferreira** [gepetojj/shelf#3]
# Description
As vezes o usuário não consegue criar a conta porque o usuário não está criado

# Screenshots
![image](https://github.com/gepetojj/shelf/assets/100143483/6bf97e09-6a75-42f6-ab93-519c9df383fd)

**Comment by gepetojj** [comment]
Provavelmente resolvido no commit 44d004f
Precisamos de mais testes para confimar

**Comment by ceduardoferreira** [comment]
Vou fazer mais testes aqui

**Comment by ceduardoferreira** [comment]
Testei e pedi pra outro user testar. 

### Bug corrigido!
