### ISSUE TITLE
BUG - marcação de pdf

### ISSUE THREAD

**Issue by ceduardoferreira** [gepetojj/shelf#4]
# Descrição
- Quando tento marcar um pdf, ele marca em outra posição da página e não está um fluxo agradável.

# Resolução
- Faça com que o usuário consiga marcar na página e a parte selecionada não mude de posição.

# Screenshots
![image](https://github.com/gepetojj/shelf/assets/100143483/8915c4d2-ced7-4eb6-9ec5-8f35870c47ce)

**Comment by gepetojj** [comment]
corrigido no commit 2d24853

**Comment by ceduardoferreira** [comment]
você trabalha demais, Deus benza
